apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-schedule-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: doctor-schedule
          image: elxpro/doctor_schedule:v2
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              value: postgres://tuevnzrq:TJGd0H4AaMmvRiJPXn5nYC4aO6H485DA@queenie.db.elephantsql.com:5432/tuevnzrq
            - name: SECRET_KEY_BASE
              value: 6JwpGyrnuipQNo8MapaxL3Q9m48HxVuCao+QFEMGHl+I8Dp8rnkltBnLw7rdr56Z
            - name: SECRET_KEY_BASE
              value: 6JwpGyrnuipQNo8MapaxL3Q9m48HxVuCao+QFEMGHl+I8Dp8rnkltBnLw7rdr56Z
            - name: POOL_SIZE
              value: "2"
            - name: GUARDIAN_SECRET
              value: jSZXHnu1mN7Y4ZY65ghBSeJIZtowq/EsBSllejDFfGCYosYJ5Faa8ZkAzoqmsjoR
            - name: SMTP_HOST
              value: smtp.ethereal.email
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USERNAME
              value: alaina.erdman@ethereal.email
            - name: SMTP_PASSWORD
              value: b4c71ee2PW4bRkKzKm
            - name: MONGO_URL
              value: mongodb+srv://guuholi:elxpro123@cluster0.mcd1g.mongodb.net/doctor_scheduler?retryWrites=true&w=majority
            - name: MONGO_POOL_SIZE
              value: "2"
            - name: REDIS_URL
              value: redis://4330767d9a7946e19331ae0c5c789d87@us1-strong-dogfish-32638.upstash.io:32638
