apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-schedule-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: doctor-schedule
          image: elxpro/doctor_schedule:v2
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: database-url
            - name: SECRET_KEY_BASE
              value: 6JwpGyrnuipQNo8MapaxL3Q9m48HxVuCao+QFEMGHl+I8Dp8rnkltBnLw7rdr56Z
            - name: SECRET_KEY_BASE
              value: 6JwpGyrnuipQNo8MapaxL3Q9m48HxVuCao+QFEMGHl+I8Dp8rnkltBnLw7rdr56Z
            - name: POOL_SIZE
              value: "2"
            - name: GUARDIAN_SECRET
              value: jSZXHnu1mN7Y4ZY65ghBSeJIZtowq/EsBSllejDFfGCYosYJ5Faa8ZkAzoqmsjoR
            - name: SMTP_HOST
              value: smtp.ethereal.email
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USERNAME
              value: alaina.erdman@ethereal.email
            - name: SMTP_PASSWORD
              value: b4c71ee2PW4bRkKzKm
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: MONGO_URL
                  name: mongo-url
            - name: MONGO_POOL_SIZE
              value: "2"
            - name: REDIS_URL
              valueFrom:
               secretKeyRef:
                key: REDIS_URL
                name: redis-url
