apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce # usado apenas para um no
  #  - ReadOnlyMany # pode ser lido por muitos nos
  #  - ReadWriteMany # pode ser lido por muitos nos
  resources:
    requests:
      storage: 1Gi
