apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  pgpassword: {{ .Values.pgpassword }}
  database-url: {{ .Values.database.url }}
  mongo-url: {{ .Values.mongo.url }}
  redis-url: {{ .Values.redisUrl }}
